# version format
version: 2.3.1.{build}.0

os: Visual Studio 2015

artifacts:
  - path: 'build/doc/*.chm'
    name: Documentation

install:
    - ps: (new-object net.webclient).DownloadFile('https://github.com/DLR-SC/tixi/releases/download/v2.2.4/TIXI-2.2.4-win32.zip', 'c:\projects\cpacs\development\TIXI-2.2.4-win32.zip')
    - cmd: 7z x -y c:\projects\cpacs\development\TIXI-2.2.4-win32.zip -oc:\projects\cpacs\tools
    - cmd: 7z x -y c:\projects\cpacs\development\3rdparty.zip -oc:\projects\cpacs\development\
    - cmd: SET PATH=c:\projects\cpacs\tools\TIXI-2.2.4-win32\bin;%PATH%
    - cmd: SET PYTHONPATH=c:\projects\cpacs\tools\TIXI-2.2.4-win32\share\tixi\python;%PYTHONPATH%
    - cmd: python -V

test_script:
    - cmd: appveyor PushArtifact "build/doc/CPACS Documentation.chm"
    - cmd: echo "running schema validation..."
    - cmd: python validate_example_file.py c:\projects\cpacs\schema\cpacs_schema.xml c:\projects\cpacs\schema\cpacs_schema.xsd

platform: Any CPU

configuration: Release

build:
    project: documentation\Cpacs_doc_project.shfbproj

